[target.thumbv7em-none-eabihf]
# replace nRF82840_xxAA with your chip as listed in `probe-rs chip list`
runner = "probe-rs run --chip nRF52840_xxAA"

[profile.debug]
debug = 2

[profile.release]
debug = 2

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "info"
